def HelloPorcupine():
    print "HelloPorcupine will start in two seconds. Watch your RaspPi."
    time.sleep(2)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    pibrella.light.yellow.on()
    time.sleep(0.3)
    pibrella.light.yellow.off()
    pibrella.light.green.on()
    time.sleep(0.3)
    pibrella.light.green.off()
    pibrella.light.on()
    time.sleep(0.3)
    pibrella.light.off()
    time.sleep(0.1)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    pibrella.light.yellow.on()
    time.sleep(0.3)
    pibrella.light.yellow.off()
    pibrella.light.green.on()
    time.sleep(0.3)
    pibrella.light.green.off()
    pibrella.light.on()
    time.sleep(0.3)
    pibrella.light.off()
    time.sleep(0.1)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    pibrella.light.yellow.on()
    time.sleep(0.3)
    pibrella.light.yellow.off()
    pibrella.light.green.on()
    time.sleep(0.3)
    pibrella.light.green.off()
    pibrella.light.on()
    time.sleep(0.3)
    pibrella.light.off()
    time.sleep(0.1)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    pibrella.light.yellow.on()
    time.sleep(0.3)
    pibrella.light.yellow.off()
    pibrella.light.green.on()
    time.sleep(0.3)
    pibrella.light.green.off()
    pibrella.light.on()
    time.sleep(0.3)
    pibrella.light.off()
    time.sleep(0.1)
    pibrella.light.red.on()
    time.sleep(0.25)
    pibrella.light.red.off()
    time.sleep(0.5)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    time.sleep(0.15)
    pibrella.light.red.on()
    time.sleep(0.3)
    pibrella.light.red.off()
    print "Finished executing HelloPorcupine."
def FadingFast():
    print "FadingFast will start in two seconds. Watch your RaspPi."
    time.sleep(2)
    pibrella.light.red.fade(50, 0, 0.25)
    pibrella.light.yellow.fade(50, 0, 0.25)
    pibrella.light.green.fade(50, 0, 0.25)
    pibrella.light.red.fade(60, 0, 0.2)
    pibrella.light.yellow.fade(60, 0, 0.2)
    pibrella.light.green.fade(60, 0, 0.2)
    pibrella.light.red.fade(70, 0, 0.15)
    pibrella.light.yellow.fade(70, 0, 0.15)
    pibrella.light.green.fade(70, 0, 0.15)
    pibrella.light.red.fade(80, 0, 0.1)
    pibrella.light.yellow.fade(80, 0, 0.1)
    pibrella.light.green.fade(80, 0, 0.1)
    pibrella.light.red.fade(83, 0, 0.1)
    pibrella.light.yellow.fade(83, 0, 0.1)
    pibrella.light.green.fade(83, 0, 0.1)
    pibrella.light.red.fade(87, 0, 0.1)
    pibrella.light.yellow.fade(87, 0, 0.1)
    pibrella.light.green.fade(87, 0, 0.1)
    pibrella.light.red.fade(90, 0, 0.1)
    pibrella.light.yellow.fade(90, 0, 0.1)
    pibrella.light.green.fade(90, 0, 0.1)
    pibrella.light.red.fade(93, 0, 0.1)
    pibrella.light.yellow.fade(93, 0, 0.1)
    pibrella.light.green.fade(93, 0, 0.1)
    pibrella.light.red.fade(97, 0, 0.1)
    pibrella.light.yellow.fade(97, 0, 0.1)
    pibrella.light.green.fade(97, 0, 0.1)
    pibrella.light.red.fade(100, 0, 0.1)
    pibrella.light.yellow.fade(100, 0, 0.1)
    pibrella.light.green.fade(100, 0, 0.1)
    pibrella.light.red.fade(100, 15, 0.1)
    pibrella.light.yellow.fade(100, 15, 0.1)
    pibrella.light.green.fade(100, 15, 0.1)
    pibrella.light.red.fade(100, 30, 0.1)
    pibrella.light.yellow.fade(100, 30, 0.1)
    pibrella.light.green.fade(100, 30, 0.1)
    pibrella.light.red.fade(100, 45, 0.1)
    pibrella.light.yellow.fade(100, 45, 0.1)
    pibrella.light.green.fade(100, 45, 0.1)
    pibrella.light.red.fade(100, 60, 0.1)
    pibrella.light.yellow.fade(100, 60, 0.1)
    pibrella.light.green.fade(100, 60, 0.1)
    pibrella.light.red.fade(100, 75, 0.1)
    pibrella.light.yellow.fade(100, 75, 0.1)
    pibrella.light.green.fade(100, 75, 0.1)
    pibrella.light.on()
    time.sleep(3)
    pibrella.light.on()
    print "Finished executing FadingFast."
def Flash():
    print "Flash will start in two seconds. Watch your RaspPi."
    time.sleep(2)
    pibrella.light.on()
    time.sleep(0.5)
    pibrella.light.off()
    time.sleep(0.5)
    pibrella.light.on()
    time.sleep(0.5)
    pibrella.light.off()
    time.sleep(0.5)
    pibrella.light.on()
    time.sleep(0.5)
    pibrella.light.off()
    time.sleep(0.5)
    pibrella.light.on()
    time.sleep(0.5)
    pibrella.light.off()
    time.sleep(0.5)
    pibrella.light.on()
    time.sleep(0.25)
    pibrella.light.off()
    time.sleep(0.25)
    pibrella.light.on()
    time.sleep(0.25)
    pibrella.light.off()
    time.sleep(0.25)
    pibrella.light.on()
    time.sleep(0.25)
    pibrella.light.off()
    time.sleep(0.25)
    pibrella.light.on()
    time.sleep(0.25)
    pibrella.light.off()
    time.sleep(0.25)
    pibrella.light.on()
    time.sleep(0.15)
    pibrella.light.off()
    time.sleep(0.15)
    pibrella.light.on()
    time.sleep(0.15)
    pibrella.light.off()
    time.sleep(0.15)
    pibrella.light.on()
    time.sleep(0.15)
    pibrella.light.off()
    time.sleep(0.15)
    pibrella.light.on()
    time.sleep(0.15)
    pibrella.light.off()
    time.sleep(0.15)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    pibrella.light.on()
    time.sleep(0.08)
    pibrella.light.off()
    time.sleep(0.08)
    print "Finished executing Flash."